const vscode=require('vscode');
const {execFile}=require('node:child_process');
const {promisify}=require('node:util');
const exec=promisify(execFile);
function activate(context){
 let active=context.workspaceState.get('activeTask');
 const bar=vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left,50);bar.command='devflow.tasks';const update=()=>{bar.text=active?`$(checklist) TASK-${active.id}`:'$(checklist) DevFlow';bar.show();};update();context.subscriptions.push(bar);
 function base(){const u=new URL(vscode.workspace.getConfiguration('devflow').get('url'));if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw Error('Use HTTPS for remote backend');return u.origin;}
 async function api(path,method='GET',body){const origin=base(),token=await context.secrets.get('token:'+origin);const r=await fetch(origin+'/api'+path,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token||''}`},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
 function command(name,fn){context.subscriptions.push(vscode.commands.registerCommand('devflow.'+name,async()=>{try{await fn();}catch(e){vscode.window.showErrorMessage('DevFlow: '+e.message);}}));}
 async function folder(){if(!vscode.workspace.isTrusted)throw Error('Trust workspace before Git operations');const folders=vscode.workspace.workspaceFolders;if(!folders?.length)throw Error('Open a Git repository first');const f=folders.length===1?folders[0]:await vscode.window.showWorkspaceFolderPick();if(!f)throw Error('No repository selected');return f.uri.fsPath;}
 async function git(args,cwd){return (await exec('git',args,{cwd:cwd||await folder(),windowsHide:true,timeout:120000,maxBuffer:2*1024*1024})).stdout.trim();}
 async function current(){if(!active)throw Error('Select a task first');active=await api('/tasks/'+active.id);await context.workspaceState.update('activeTask',active);update();return active;}
 command('login',async()=>{const email=await vscode.window.showInputBox({prompt:'DevFlow email'});if(!email)return;const password=await vscode.window.showInputBox({prompt:'DevFlow password',password:true});if(!password)return;const data=await api('/auth/login','POST',{email,password});await context.secrets.store('token:'+base(),data.token);vscode.window.showInformationMessage('Signed in to DevFlow');});
 command('logout',async()=>{await api('/auth/logout','POST',{});await context.secrets.delete('token:'+base());active=undefined;await context.workspaceState.update('activeTask',undefined);update();});
 command('tasks',async()=>{const tasks=await api('/tasks/mine');const picked=await vscode.window.showQuickPick(tasks.map(t=>({label:`TASK-${t.id} ${t.title}`,description:t.status,task:t})),{placeHolder:'Select your active task'});if(picked){active=picked.task;await context.workspaceState.update('activeTask',active);update();}});
 command('details',async()=>{const t=await current();const document=await vscode.workspace.openTextDocument({language:'markdown',content:`# TASK-${t.id}: ${t.title}\n\nStatus: ${t.status}\nPriority: ${t.priority}\nDue: ${t.due_date||'—'}\n\n${t.description}\n\n## Links\n${t.links.map(l=>`${l.kind}: ${l.url}`).join('\n')}\n\n## Comments\n${t.comments.map(c=>c.body).join('\n\n')}`});await vscode.window.showTextDocument(document);});
 command('status',async()=>{const t=await current(),board=await api(`/projects/${t.project_id}/board`);const pick=await vscode.window.showQuickPick(board.columns.map(c=>({label:c.name,id:c.id})));if(pick){active=await api('/tasks/'+t.id,'PATCH',{version:t.version,column_id:pick.id});update();}});
 command('branch',async()=>{const t=await current();const slug=t.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||'work';const name=await vscode.window.showInputBox({prompt:'New local task branch',value:`task/${t.id}-${slug}`});if(!name)return;const cwd=await folder();await git(['check-ref-format','--branch',name],cwd);await git(['switch','-c',name],cwd);vscode.window.showInformationMessage('Created '+name);});
 async function prepare(){const t=await current();return vscode.window.showInputBox({prompt:'Commit message',value:`TASK-${t.id} ${t.title}`,validateInput:v=>v.startsWith(`TASK-${t.id} `)?null:'Keep the TASK reference'});}
 command('prepareCommit',async()=>{const message=await prepare();if(message){await vscode.env.clipboard.writeText(message);const ext=vscode.extensions.getExtension('vscode.git');if(ext){const api=(await ext.activate()).getAPI(1);if(api.repositories.length===1)api.repositories[0].inputBox.value=message;}vscode.window.showInformationMessage('Commit message copied and prepared');}});
 command('commit',async()=>{const message=await prepare();if(!message)return;const cwd=await folder();const files=await git(['diff','--cached','--name-only'],cwd);if(!files)throw Error('Stage changes in Source Control first');const choice=await vscode.window.showWarningMessage(`Commit staged files?\n${files}`,{modal:true},'Commit');if(choice==='Commit'){await git(['commit','-m',message],cwd);vscode.window.showInformationMessage('Committed staged changes');}});
 command('push',async()=>{await current();const cwd=await folder(),branch=await git(['branch','--show-current'],cwd);if(!branch)throw Error('Detached HEAD cannot be pushed here');const choice=await vscode.window.showWarningMessage(`Push ${branch} to origin?`,{modal:true},'Push');if(choice==='Push'){await git(['push','--set-upstream','origin',branch],cwd);vscode.window.showInformationMessage('Branch pushed');}});
}
module.exports={activate,deactivate(){}};
