import http from 'node:http';
import {readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {randomBytes} from 'node:crypto';
import {all,get,run,tx,id,now,fail,required,hash,password,verifyPassword,equal,crypt,signature,access,project,task,enqueue,audit,emit,move,mentions} from './core.js';
import {external,pages,slackAction} from './integrations.js';
const base=()=>((process.env.PUBLIC_URL||'http://localhost:3000').replace(/\/+$/,''));
const routes=[];
function route(method,path,handler,options={}){const names=[];const pattern=new RegExp('^'+path.replace(/:([\w]+)/g,(_,n)=>{names.push(n);return '([^/]+)';})+'$');routes.push({method,path,pattern,names,handler,...options});}
const boardColumns=pid=>all('SELECT c.* FROM columns c JOIN boards b ON b.id=c.board_id WHERE b.project_id=? ORDER BY c.position',pid);
function checkedAssignee(org,uid){if(uid&&!get('SELECT 1 FROM members WHERE org_id=? AND user_id=?',org,uid))fail(400,'Assignee must belong to organization');return uid||null;}
function taskFields(b,p){if(b.priority&&!['low','normal','high','urgent'].includes(b.priority))fail(400,'Invalid priority');if(b.labels&&(!Array.isArray(b.labels)||b.labels.some(x=>typeof x!=='string'||x.length>100)))fail(400,'Invalid labels');if(b.due_date&&Number.isNaN(Date.parse(b.due_date)))fail(400,'Invalid due date');if(b.parent_id&&!get('SELECT 1 FROM tasks WHERE id=? AND project_id=? AND deleted_at IS NULL',b.parent_id,p.id))fail(400,'Invalid parent task');if(b.assignee)checkedAssignee(p.org_id,b.assignee);}
route('GET','/api/health',()=>({ok:!!get('SELECT 1')}),{public:true});
route('GET','/api/endpoints',()=>routes.map(r=>({method:r.method,path:r.path,public:!!r.public})));
route('POST','/api/auth/register',({b})=>{
 const email=required(b.email,'email').toLowerCase(),name=required(b.name,'name');if(!/^[\w.-]{2,40}$/.test(name)||!email.includes('@')||typeof b.password!=='string'||b.password.length<10||b.password.length>200)fail(400,'Use a valid email, username and 10–200 character password');
 if(get('SELECT 1 FROM users WHERE email=? OR name=?',email,name))fail(409,'Email or username already exists');const uid=id();run('INSERT INTO users VALUES(?,?,?,?)',uid,email,name,password(b.password));return {id:uid,email,name};
},{public:true});
route('POST','/api/auth/login',({b})=>{
 const u=get('SELECT * FROM users WHERE email=?',required(b.email).toLowerCase());const candidate=typeof b.password==='string'&&b.password.length<=200?b.password:'';if(!u||!verifyPassword(candidate,u.password))fail(401,'Invalid credentials');
 const token=randomBytes(32).toString('hex');run('INSERT INTO sessions VALUES(?,?,?)',hash(token),u.id,now()+7*86400000);return {token,user:{id:u.id,name:u.name,email:u.email}};
},{public:true});
route('POST','/api/auth/logout',({token})=>{run('DELETE FROM sessions WHERE token=?',hash(token));return {ok:true};});
route('GET','/api/me',({user})=>get('SELECT id,name,email FROM users WHERE id=?',user));
route('GET','/api/organizations',({user})=>all('SELECT o.*,m.role FROM organizations o JOIN members m ON m.org_id=o.id WHERE m.user_id=?',user));
route('POST','/api/organizations',({user,b})=>{const oid=id();run('INSERT INTO organizations VALUES(?,?)',oid,required(b.name));run('INSERT INTO members VALUES(?,?,?)',oid,user,'Owner');audit(oid,user,'organization.created',{});return {id:oid};});
route('GET','/api/organizations/:org/members',({user,p})=>{access(user,p.org);return all('SELECT u.id,u.name,u.email,m.role FROM members m JOIN users u ON u.id=m.user_id WHERE org_id=?',p.org);});
route('POST','/api/organizations/:org/members',({user,p,b})=>{const role=b.role||'Member';const caller=access(user,p.org,true,true);if(!['Admin','Member','Viewer'].includes(role)||role==='Admin'&&caller.role!=='Owner')fail(403,'Invalid role grant');const u=get('SELECT id FROM users WHERE email=?',required(b.email).toLowerCase());if(!u)fail(404,'User must register first');if(get('SELECT role FROM members WHERE org_id=? AND user_id=?',p.org,u.id)?.role==='Owner')fail(403,'Cannot change owner');run('INSERT INTO members VALUES(?,?,?) ON CONFLICT(org_id,user_id) DO UPDATE SET role=excluded.role',p.org,u.id,role);audit(p.org,user,'membership.updated',{user_id:u.id,role});return {ok:true};});
route('GET','/api/organizations/:org/teams',({user,p})=>{access(user,p.org);return all('SELECT * FROM teams WHERE org_id=?',p.org).map(team=>({...team,members:all('SELECT u.id,u.name FROM team_members tm JOIN users u ON u.id=tm.user_id WHERE tm.team_id=? ORDER BY u.name',team.id)}));});
route('POST','/api/organizations/:org/teams',({user,p,b})=>{access(user,p.org,true,true);const tid=id();run('INSERT INTO teams VALUES(?,?,?)',tid,p.org,required(b.name));for(const uid of b.members||[]){checkedAssignee(p.org,uid);run('INSERT INTO team_members VALUES(?,?)',tid,uid);}audit(p.org,user,'team.created',{id:tid});return {id:tid};});
route('GET','/api/organizations/:org/projects',({user,p})=>{access(user,p.org);return all('SELECT * FROM projects WHERE org_id=? AND deleted_at IS NULL',p.org);});
route('POST','/api/organizations/:org/projects',({user,p,b})=>{access(user,p.org,true);const pid=id(),bid=id();run('INSERT INTO projects(id,org_id,name) VALUES(?,?,?)',pid,p.org,required(b.name));run('INSERT INTO boards VALUES(?,?,?)',bid,pid,'Main board');['Backlog','Todo','In Progress','Review','Done'].forEach((name,i)=>run('INSERT INTO columns VALUES(?,?,?,?)',id(),bid,name,i));for(const [trigger,condition,action,value] of [['pr.opened',null,'set_status','Review'],['pr.merged','Review','set_status','Done'],['pr.merged','In Progress','set_status','Done'],['ci.failed',null,'comment','GitHub CI failed. Inspect the linked check.']])run('INSERT INTO rules(id,project_id,trigger,condition_status,action,value) VALUES(?,?,?,?,?,?)',id(),pid,trigger,condition,action,value);emit(pid,'project.created',{},null,user);return {id:pid,board_id:bid};});
route('PATCH','/api/projects/:pid',async({user,p,b})=>{const pr=project(user,p.pid,true,true);if(b.repo!==undefined&&b.repo!==null){if(!/^[\w.-]+\/[\w.-]+$/.test(b.repo))fail(400,'Expected owner/repository');const repo=await external('github',pr.org_id,`/repos/${b.repo}`);b.repo=required(repo.full_name,'GitHub repository name');}if(b.slack_channel!==undefined&&b.slack_channel!==null&&!/^[CG][A-Z0-9]+$/.test(b.slack_channel))fail(400,'Invalid channel ID');tx(()=>{const current=project(user,p.pid,true,true);run('UPDATE projects SET repo=?,slack_channel=? WHERE id=?',b.repo===undefined?current.repo:b.repo,b.slack_channel===undefined?current.slack_channel:b.slack_channel,pr.id);audit(pr.org_id,user,'project.integrations_updated',{repo:b.repo,slack_channel:b.slack_channel});if(b.repo)enqueue(`resync:${id()}`,'resync',{project_id:pr.id});});return {ok:true};},{async:true});
route('DELETE','/api/projects/:pid',({user,p})=>{const pr=project(user,p.pid,true,true);run('UPDATE projects SET deleted_at=? WHERE id=?',now(),pr.id);audit(pr.org_id,user,'project.deleted',{id:pr.id});return {ok:true};});
route('GET','/api/projects/:pid/board',({user,p})=>{project(user,p.pid);return {boards:all('SELECT * FROM boards WHERE project_id=?',p.pid),columns:boardColumns(p.pid),tasks:all('SELECT t.*,c.name AS status FROM tasks t JOIN columns c ON c.id=t.column_id WHERE t.project_id=? AND t.deleted_at IS NULL ORDER BY t.id',p.pid)};});
route('POST','/api/projects/:pid/columns',({user,p,b})=>{project(user,p.pid,true);const board=get('SELECT * FROM boards WHERE id=? AND project_id=?',b.board_id||'',p.pid);if(!board)fail(400,'Invalid board');const cid=id();run('INSERT INTO columns VALUES(?,?,?,?)',cid,board.id,required(b.name),boardColumns(p.pid).length);emit(p.pid,'column.created',{id:cid,name:b.name},null,user);return {id:cid};});
route('PUT','/api/projects/:pid/columns/order',({user,p,b})=>{project(user,p.pid,true);const columns=boardColumns(p.pid);if(!Array.isArray(b.ids)||b.ids.length!==columns.length||new Set(b.ids).size!==columns.length||b.ids.some(x=>!columns.some(c=>c.id===x)))fail(400,'Provide each column ID once');b.ids.forEach((cid,i)=>run('UPDATE columns SET position=? WHERE id=?',i,cid));emit(p.pid,'columns.reordered',{ids:b.ids},null,user);return {ok:true};});
route('GET','/api/tasks/mine',({user})=>all('SELECT t.*,c.name AS status FROM tasks t JOIN columns c ON c.id=t.column_id JOIN projects p ON p.id=t.project_id JOIN members m ON m.org_id=p.org_id WHERE t.assignee=? AND m.user_id=? AND t.deleted_at IS NULL AND p.deleted_at IS NULL',user,user));
route('POST','/api/projects/:pid/tasks',({user,p,b})=>{const pr=project(user,p.pid,true);taskFields(b,pr);const columns=boardColumns(p.pid),cid=b.column_id||columns[0].id;if(!columns.some(c=>c.id===cid))fail(400,'Invalid column');const result=run('INSERT INTO tasks(project_id,column_id,parent_id,title,description,priority,assignee,labels,due_date) VALUES(?,?,?,?,?,?,?,?,?)',p.pid,cid,b.parent_id||null,required(b.title),b.description||'',b.priority||'normal',checkedAssignee(pr.org_id,b.assignee),JSON.stringify(b.labels||[]),b.due_date||null);const tid=Number(result.lastInsertRowid);emit(p.pid,'task.created',{title:b.title},tid,user);if(b.assignee)emit(p.pid,'task.assigned',{assignee:b.assignee},tid,user);return task(user,tid);});
route('GET','/api/tasks/:tid',({user,p})=>{const t=task(user,p.tid);return {...t,labels:JSON.parse(t.labels),links:all('SELECT * FROM task_links WHERE task_id=?',t.id),comments:all('SELECT * FROM comments WHERE task_id=? ORDER BY created_at',t.id),activity:all('SELECT * FROM events WHERE task_id=? ORDER BY id DESC LIMIT 100',t.id)};});
route('PATCH','/api/tasks/:tid',({user,p,b})=>{const t=task(user,p.tid,true),pr=project(user,t.project_id,true);if(b.version!==t.version)fail(409,'Task changed; refresh and retry');taskFields(b,pr);const cid=b.column_id||t.column_id;if(!boardColumns(t.project_id).some(c=>c.id===cid))fail(400,'Invalid column');if(b.title!==undefined)required(b.title);run('UPDATE tasks SET title=?,description=?,priority=?,assignee=?,labels=?,due_date=?,column_id=?,version=version+1 WHERE id=? AND version=?',b.title??t.title,b.description??t.description,b.priority??t.priority,b.assignee===undefined?t.assignee:b.assignee||null,b.labels?JSON.stringify(b.labels):t.labels,b.due_date===undefined?t.due_date:b.due_date||null,cid,t.id,t.version);emit(t.project_id,'task.updated',{fields:Object.keys(b)},t.id,user);if(cid!==t.column_id)emit(t.project_id,'task.status_changed',{from:t.status,to:get('SELECT name FROM columns WHERE id=?',cid).name},t.id,user);if(b.assignee!==undefined&&b.assignee!==t.assignee)emit(t.project_id,'task.assigned',{assignee:b.assignee},t.id,user);return task(user,t.id);});
route('DELETE','/api/tasks/:tid',({user,p,b})=>{const t=task(user,p.tid,true);if(b.version!==t.version)fail(409,'Task changed');run('UPDATE tasks SET deleted_at=?,version=version+1 WHERE id=?',now(),t.id);emit(t.project_id,'task.deleted',{},t.id,user);return {ok:true};});
route('POST','/api/tasks/:tid/comments',({user,p,b})=>{const t=task(user,p.tid,true),body=required(b.body),cid=id();run('INSERT INTO comments VALUES(?,?,?,?,?)',cid,t.id,user,body,now());emit(t.project_id,'task.comment',{body,mentions:mentions(t.project_id,body)},t.id,user);return {id:cid};});
route('POST','/api/tasks/:tid/links',({user,p,b})=>{const t=task(user,p.tid,true);if(!['commit','pr','issue'].includes(b.kind)||!/^https:\/\/github\.com\//.test(b.url||''))fail(400,'Invalid GitHub link');run('INSERT OR IGNORE INTO task_links VALUES(?,?,?,?)',t.id,b.kind,required(b.external_id),b.url);emit(t.project_id,'task.linked',b,t.id,user);return {ok:true};});
route('GET','/api/projects/:pid/messages',({user,p,q})=>{project(user,p.pid);return all('SELECT m.*,u.name FROM messages m JOIN users u ON u.id=m.user_id WHERE project_id=? AND m.created_at<? ORDER BY m.created_at DESC LIMIT 100',p.pid,Number(q.get('before'))||now()+1);});
route('POST','/api/projects/:pid/messages',({user,p,b})=>{project(user,p.pid,true);const body=required(b.body),mid=id(),links=mentions(p.pid,body);if(b.reply_to&&!get('SELECT id FROM messages WHERE id=? AND project_id=?',b.reply_to,p.pid))fail(400,'Reply must be in same project');run('INSERT INTO messages VALUES(?,?,?,?,?,?,?)',mid,p.pid,user,body,b.reply_to||null,JSON.stringify(links),now());emit(p.pid,'message.created',{id:mid,body,mentions:links},null,user);return {id:mid,links};});
route('GET','/api/projects/:pid/activity',({user,p,q})=>{project(user,p.pid);return all('SELECT * FROM events WHERE project_id=? AND id>? ORDER BY id LIMIT 200',p.pid,Number(q.get('after'))||0);});
route('GET','/api/notifications',({user})=>all('SELECT n.*,e.type,e.payload,e.project_id,e.task_id,e.created_at FROM notifications n JOIN events e ON e.id=n.event_id JOIN projects p ON p.id=e.project_id JOIN members m ON m.org_id=p.org_id AND m.user_id=n.user_id WHERE n.user_id=? AND p.deleted_at IS NULL ORDER BY e.id DESC LIMIT 200',user));
route('PATCH','/api/notifications/:nid',({user,p,b})=>{run('UPDATE notifications SET read_at=? WHERE id=? AND user_id=?',b.read===false?null:now(),p.nid,user);return {ok:true};});
route('GET','/api/projects/:pid/rules',({user,p})=>{project(user,p.pid);return all('SELECT * FROM rules WHERE project_id=?',p.pid);});
route('POST','/api/projects/:pid/rules',({user,p,b})=>{project(user,p.pid,true,true);if(!['set_status','comment','slack'].includes(b.action))fail(400,'Invalid action');if(b.action==='set_status'&&!boardColumns(p.pid).some(c=>c.name===b.value))fail(400,'Unknown destination status');const rid=id();run('INSERT INTO rules(id,project_id,trigger,condition_status,action,value) VALUES(?,?,?,?,?,?)',rid,p.pid,required(b.trigger),b.condition_status||null,b.action,required(b.value));emit(p.pid,'rule.created',{id:rid},null,user);return {id:rid};});
route('DELETE','/api/projects/:pid/rules/:rid',({user,p})=>{project(user,p.pid,true,true);run('UPDATE rules SET enabled=0 WHERE id=? AND project_id=?',p.rid,p.pid);emit(p.pid,'rule.disabled',{id:p.rid},null,user);return {ok:true};});
route('GET','/api/organizations/:org/audit',({user,p})=>{access(user,p.org,false,true);return all('SELECT * FROM audit WHERE org_id=? ORDER BY id DESC LIMIT 200',p.org);});
route('GET','/api/organizations/:org/integrations',({user,p})=>{access(user,p.org);return all('SELECT provider,external_id FROM integrations WHERE org_id=?',p.org);});
route('GET','/api/organizations/:org/slack/identities',({user,p})=>{access(user,p.org);return all('SELECT user_id,external_id AS slack_user_id FROM identities WHERE provider=? AND org_id=? AND user_id=?','slack',p.org,user);});
route('DELETE','/api/organizations/:org/integrations/:provider',({user,p})=>{access(user,p.org,true,true);run('DELETE FROM integrations WHERE org_id=? AND provider=?',p.org,p.provider);audit(p.org,user,'integration.disconnected',{provider:p.provider});return {ok:true};});
route('GET','/api/organizations/:org/github/repositories',async({user,p})=>{access(user,p.org);return pages(p.org,'/user/repos?sort=updated');},{async:true});
route('GET','/api/projects/:pid/github/objects',({user,p})=>{project(user,p.pid);return all('SELECT * FROM external_objects WHERE project_id=?',p.pid);});
route('POST','/api/projects/:pid/github/resync',({user,p})=>{project(user,p.pid,true,true);enqueue(`resync:${id()}`,'resync',{project_id:p.pid});return {queued:true};});
route('POST','/api/projects/:pid/github/actions',async({user,p,b})=>{
 const pr=project(user,p.pid,true),root=`/repos/${pr.repo}`;if(!pr.repo)fail(409,'Map a repository first');let path,method='POST',body;
 const number=Number(b.number);if(['close_issue','comment','labels','merge'].includes(b.action)&&(!Number.isSafeInteger(number)||number<1))fail(400,'Invalid issue/PR number');
 if(b.action==='create_issue'){path='/issues';body={title:required(b.title),body:b.body||''};}
 else if(b.action==='close_issue'){path=`/issues/${number}`;method='PATCH';body={state:'closed'};}
 else if(b.action==='comment'){path=`/issues/${number}/comments`;body={body:required(b.body)};}
 else if(b.action==='labels'){if(!Array.isArray(b.labels)||b.labels.some(x=>typeof x!=='string'))fail(400,'Invalid labels');path=`/issues/${number}/labels`;body={labels:b.labels};}
 else if(b.action==='branch'){if(!/^[\w./-]+$/.test(b.name||'')||b.name.includes('..')||! /^[a-f0-9]{40}$/i.test(b.sha||''))fail(400,'Invalid branch or SHA');path='/git/refs';body={ref:`refs/heads/${b.name}`,sha:b.sha};}
 else if(b.action==='merge'){access(user,pr.org_id,true,true);const pull=await external('github',pr.org_id,`${root}/pulls/${number}`);if(pull.draft||pull.state!=='open'||pull.mergeable!==true||pull.mergeable_state!=='clean'||b.sha!==pull.head.sha)fail(409,'PR must be clean, mergeable and match supplied head SHA');path=`/pulls/${number}/merge`;method='PUT';body={sha:b.sha,merge_method:'squash'};}
 else fail(400,'Unknown action');
 const result=await external('github',pr.org_id,root+path,method,body);tx(()=>{emit(pr.id,'github.action',{action:b.action,number:result.number||number||null},null,user);enqueue(`resync:${id()}`,'resync',{project_id:pr.id});});return result;
},{async:true});
route('POST','/api/organizations/:org/oauth/:provider',({user,p})=>{
 if(!['github','slack'].includes(p.provider))fail(404,'Unknown provider');access(user,p.org,true,true);const prefix=p.provider.toUpperCase(),client=process.env[`${prefix}_CLIENT_ID`],secret=process.env[`${prefix}_CLIENT_SECRET`];if(!client||!secret)fail(503,'OAuth client is not configured');const state=randomBytes(32).toString('hex');run('INSERT INTO oauth_states VALUES(?,?,?,?,?)',hash(state),user,p.org,p.provider,now()+600000);
 const params=new URLSearchParams({client_id:client,state,redirect_uri:`${base()}/oauth/${p.provider}/callback`,scope:p.provider==='github'?'repo read:user':'chat:write'});
 return {url:(p.provider==='github'?'https://github.com/login/oauth/authorize':'https://slack.com/oauth/v2/authorize')+'?'+params};
});
route('GET','/oauth/:provider/callback',async({p,q})=>{
 const state=tx(()=>{const s=get('SELECT * FROM oauth_states WHERE state=? AND provider=? AND expires>?',hash(q.get('state')||''),p.provider,now());if(!s)fail(400,'Invalid or expired OAuth state');access(s.user_id,s.org_id,true,true);run('DELETE FROM oauth_states WHERE state=?',s.state);return s;});
 const prefix=p.provider.toUpperCase(),client=process.env[`${prefix}_CLIENT_ID`],secret=process.env[`${prefix}_CLIENT_SECRET`];if(!client||!secret)fail(503,'OAuth client is not configured');const redirectUri=`${base()}/oauth/${p.provider}/callback`,form=new URLSearchParams({client_id:client,client_secret:secret,code:required(q.get('code')),redirect_uri:redirectUri});
 let response,data;try{response=await fetch(p.provider==='github'?'https://github.com/login/oauth/access_token':'https://slack.com/api/oauth.v2.access',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body:form,signal:AbortSignal.timeout(15000)});data=await response.json();}catch(error){console.error(`OAuth ${p.provider} token exchange network failure`,error.cause?.code||error.code||error.name||'network_error');fail(502,`${p.provider} OAuth token exchange unavailable`);}if(!response.ok||data.ok===false||!data.access_token){const providerError=String(data?.error||data?.message||`HTTP ${response.status}`).slice(0,120);console.error(`OAuth ${p.provider} token exchange rejected`,providerError);fail(502,`${p.provider} OAuth authorization failed: ${providerError}`);}
 let externalId=data.team?.id||null,identity=data.authed_user?.id;
 if(p.provider==='github'){const r=await fetch('https://api.github.com/user',{headers:{Authorization:`Bearer ${data.access_token}`,Accept:'application/json'},signal:AbortSignal.timeout(15000)});if(!r.ok)fail(502,'Cannot read GitHub identity');externalId=String((await r.json()).id);identity=externalId;}
 tx(()=>{access(state.user_id,state.org_id,true,true);run('INSERT INTO integrations VALUES(?,?,?,?) ON CONFLICT(org_id,provider) DO UPDATE SET token=excluded.token,external_id=excluded.external_id',state.org_id,p.provider,crypt(data.access_token),externalId);if(identity)run('INSERT INTO identities VALUES(?,?,?,?) ON CONFLICT(provider,external_id,org_id) DO UPDATE SET user_id=excluded.user_id',p.provider,identity,state.org_id,state.user_id);audit(state.org_id,state.user_id,'integration.connected',{provider:p.provider});});return {redirect:`${base()}/?integration=${encodeURIComponent(p.provider)}&status=connected`};
},{public:true,async:true});
route('POST','/api/organizations/:org/slack/identities',({user,p,b})=>{access(user,p.org,true,true);checkedAssignee(p.org,b.user_id);if(!/^[UW][A-Z0-9]+$/.test(b.slack_user_id||''))fail(400,'Invalid Slack user ID');run('INSERT INTO identities VALUES(?,?,?,?) ON CONFLICT(provider,external_id,org_id) DO UPDATE SET user_id=excluded.user_id','slack',b.slack_user_id,p.org,b.user_id);audit(p.org,user,'slack.identity_linked',{slack_user_id:b.slack_user_id,user_id:b.user_id});return {ok:true};});
route('POST','/webhooks/github',({req,raw,b})=>{if(!equal(signature(process.env.GITHUB_WEBHOOK_SECRET,raw),req.headers['x-hub-signature-256']))fail(401,'Invalid signature');const delivery=required(req.headers['x-github-delivery'],'delivery ID');enqueue(`github:${delivery}`,'github',{event:req.headers['x-github-event']||'',body:b});return {accepted:true};},{public:true});
route('POST','/webhooks/slack',({req,raw,b})=>{const stamp=req.headers['x-slack-request-timestamp'];if(!stamp||Math.abs(now()/1000-Number(stamp))>300||!Number.isFinite(Number(stamp)))fail(401,'Expired Slack request');if(!equal(signature(process.env.SLACK_SIGNING_SECRET,`v0:${stamp}:${raw}`,'v0='),req.headers['x-slack-signature']))fail(401,'Invalid signature');if(b.type==='url_verification')return {challenge:b.challenge};if(b.payload){const key=hash(raw);if(get('SELECT 1 FROM idempotency WHERE user_id=? AND key=?','slack',key))return {ok:true};slackAction(JSON.parse(b.payload));run('INSERT INTO idempotency VALUES(?,?,?,?)','slack',key,key,'{}');}return {ok:true};},{public:true});
route('GET','/api/organizations/:org/jobs',({user,p})=>{access(user,p.org,false,true);const pids=all('SELECT id FROM projects WHERE org_id=?',p.org).map(x=>x.id);return all("SELECT * FROM jobs WHERE status IN ('dead','pending','running') ORDER BY id DESC").filter(j=>{const d=JSON.parse(j.payload);return pids.includes(d.project_id)||j.kind==='event'&&pids.includes(get('SELECT project_id FROM events WHERE id=?',d.id)?.project_id)||j.kind==='github'&&all('SELECT repo FROM projects WHERE org_id=?',p.org).some(p=>p.repo&&p.repo===d.body.repository?.full_name);}).map(({payload,...j})=>j);});
route('POST','/api/projects/:pid/jobs/:jid/retry',({user,p})=>{project(user,p.pid,true,true);const j=get("SELECT * FROM jobs WHERE id=? AND status='dead'",Number(p.jid));if(!j)fail(404,'Dead job not found');const d=JSON.parse(j.payload);const pid=d.project_id||(j.kind==='event'?get('SELECT project_id FROM events WHERE id=?',d.id)?.project_id:j.kind==='github'?get('SELECT id FROM projects WHERE repo=?',d.body.repository?.full_name||'')?.id:null);if(pid!==p.pid)fail(403,'Wrong project');run("UPDATE jobs SET status='pending',attempts=0,available_at=? WHERE id=?",now(),j.id);emit(p.pid,'job.retried',{job_id:j.id},null,user);return {ok:true};});
const limits=new Map();
route('GET','/api/projects/:pid/stream',({user,p,q,req,res,token})=>{
 project(user,p.pid);let cursor=Number(q.get('after'))||0;
 res.writeHead(200,{'Content-Type':'text/event-stream','Connection':'keep-alive','X-Accel-Buffering':'no'});
 const send=()=>{try{if(!get('SELECT 1 FROM sessions WHERE token=? AND expires>?',hash(token),now()))throw Error('Expired session');project(user,p.pid);const events=all('SELECT * FROM events WHERE project_id=? AND id>? ORDER BY id LIMIT 100',p.pid,cursor);for(const e of events){res.write(`id: ${e.id}\ndata: ${JSON.stringify(e)}\n\n`);cursor=e.id;}res.write(': heartbeat\n\n');}catch{clearInterval(timer);res.end();}};
 const timer=setInterval(send,1500);send();res.on('close',()=>clearInterval(timer));
},{stream:true});
function rateLimit(req,path){const key=(req.socket.remoteAddress||'')+':'+(path.startsWith('/api/auth')?'auth':'api');const limit=path.startsWith('/api/auth')?30:1000;const slot=Math.floor(now()/60000),entry=limits.get(key);if(!entry||entry.slot!==slot)limits.set(key,{slot,count:1});else if(++entry.count>limit)fail(429,'Rate limit exceeded');if(limits.size>10000)for(const [k,v]of limits)if(v.slot!==slot)limits.delete(k);}
export const server=http.createServer(async(req,res)=>{
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'");
 try{
 const url=new URL(req.url,'http://localhost');rateLimit(req,url.pathname);
 if(req.method==='GET'&&['/','/app.js','/style.css'].includes(url.pathname)){const file=url.pathname==='/'?'index.html':url.pathname.slice(1);res.setHeader('Content-Type',file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.js')?'application/javascript':'text/css');res.end(readFileSync(new URL(`../public/${file}`,import.meta.url)));return;}
 const r=routes.find(r=>r.method===req.method&&r.pattern.test(url.pathname));if(!r)fail(404,'Endpoint not found');const match=url.pathname.match(r.pattern),p=Object.fromEntries(r.names.map((n,i)=>[n,decodeURIComponent(match[i+1])]));
 const token=req.headers.authorization?.replace(/^Bearer /,'')||'';const session=get('SELECT user_id FROM sessions WHERE token=? AND expires>?',hash(token),now());if(!r.public&&!session)fail(401,'Login required');
 const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>2*1024*1024)fail(413,'Body too large');chunks.push(chunk);}const raw=Buffer.concat(chunks).toString('utf8');
 let b={};try{b=raw?(req.headers['content-type']?.includes('application/x-www-form-urlencoded')?Object.fromEntries(new URLSearchParams(raw)):JSON.parse(raw)):{};}catch{fail(400,'Invalid request body');}if(!b||typeof b!=='object'||Array.isArray(b))fail(400,'Expected object');
 const context={req,res,p,q:url.searchParams,b,raw,token,user:session?.user_id};
 if(r.stream){r.handler(context);return;}
 let result;
 if(r.async)result=await r.handler(context);else result=tx(()=>{
 const key=req.headers['idempotency-key'];const fingerprint=hash(req.method+url.pathname+raw);if(key&&session&&req.method!=='GET'){const old=get('SELECT * FROM idempotency WHERE user_id=? AND key=?',session.user_id,key);if(old){if(old.request_hash!==fingerprint)fail(409,'Idempotency key reused with another request');return JSON.parse(old.response);}}
 const out=r.handler(context);if(key&&session&&req.method!=='GET')run('INSERT INTO idempotency VALUES(?,?,?,?)',session.user_id,key,fingerprint,JSON.stringify(out));return out;
 });if(result?.redirect){res.writeHead(result.status||303,{'Location':result.redirect,'Cache-Control':'no-store'});res.end();return;}res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(result));
 }catch(e){res.statusCode=e.status||(e.code?.startsWith('ERR_SQLITE')?400:500);res.setHeader('Content-Type','application/json; charset=utf-8');if(res.statusCode===500)console.error(e);res.end(JSON.stringify({error:res.statusCode===500?'Internal server error':e.status?e.message:'Invalid or conflicting data'}));}
});
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)server.listen(Number(process.env.PORT)||3000,'0.0.0.0',()=>console.log(`DevFlow listening on ${base()}`));
