import {pathToFileURL} from 'node:url';
import {get,all,run,tx,now,enqueue,emit} from './core.js';
import {githubDelivery,processEvent,sendSlack,resync} from './integrations.js';
export async function tick(){
 const job=tx(()=>{const j=get("SELECT * FROM jobs WHERE (status='pending' AND available_at<=?) OR (status='running' AND lease_until<?) ORDER BY id LIMIT 1",now(),now());if(j)run("UPDATE jobs SET status='running',lease_until=?,attempts=attempts+1 WHERE id=?",now()+60000,j.id);return j;});if(!job)return false;
 const heartbeat=setInterval(()=>run("UPDATE jobs SET lease_until=? WHERE id=? AND status='running'",now()+60000,job.id),20000);
 try{const data=JSON.parse(job.payload);if(['github','event'].includes(job.kind))tx(()=>{if(job.kind==='github')githubDelivery(data);else processEvent(data.id);run("UPDATE jobs SET status='done',lease_until=NULL,error=NULL WHERE id=?",job.id);});else{if(job.kind==='slack')await sendSlack(data);else if(job.kind==='resync')await resync(data.project_id);else throw Error('Unknown job kind');run("UPDATE jobs SET status='done',lease_until=NULL,error=NULL WHERE id=?",job.id);}}
 catch(e){const terminal=e.retryable===false;const exhausted=job.attempts+1>=6;run('UPDATE jobs SET status=?,available_at=?,lease_until=NULL,error=? WHERE id=?',terminal||exhausted?'dead':'pending',terminal?now():Math.max(now()+Math.min(300000,1000*2**job.attempts)+Math.random()*1000,e.retryAt||0),String(e.message).slice(0,500),job.id);}
 finally{clearInterval(heartbeat);}return true;
}
export function schedule(){tx(()=>{for(const p of all('SELECT id FROM projects WHERE repo IS NOT NULL AND deleted_at IS NULL'))enqueue(`resync:${p.id}:${Math.floor(now()/300000)}`,'resync',{project_id:p.id});for(const t of all('SELECT t.* FROM tasks t JOIN columns c ON c.id=t.column_id JOIN projects p ON p.id=t.project_id WHERE t.deleted_at IS NULL AND p.deleted_at IS NULL AND t.due_date IS NOT NULL AND c.name<>?', 'Done'))if(Date.parse(t.due_date)<now())emit(t.project_id,'task.deadline',{},t.id,null,'scheduler',`deadline:${t.id}:${t.due_date}`);});}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){console.log('DevFlow worker started');let stop=false;process.on('SIGTERM',()=>{stop=true;});process.on('SIGINT',()=>{stop=true;});let next=0;while(!stop){if(now()>next){schedule();next=now()+60000;}if(!await tick())await new Promise(r=>setTimeout(r,500));}}
